### ISSUE TITLE
Optifabric crashing when joining a world

### ISSUE THREAD

**Issue by Proaman7603** [FCL-Team/FoldCraftLauncher#310]
### Launcher Version

1.1.5 don't know ig

### Device Information

Poco c3

### Problem Description

I am using some mods with optifabric and when I join a world it says saving world and crashes

### Java

Automatic set

### Renderer

Holy

### Game Version

1.20.1

### Modifications Made to the Game

Optifine hd 5 and 6

### Game Crash Report

[crash-2024-03-17_12.32.23-client.txt](https://github.com/FCL-Team/FoldCraftLauncher/files/14626488/crash-2024-03-17_12.32.23-client.txt)

### Launcher Crash Report

No

### Launcher Log File

[latest_game.log](https://github.com/FCL-Team/FoldCraftLauncher/files/14626489/latest_game.log)

Pls solve it fast

**Comment by root-S7** [comment]
OptiFine Fabric install？？？

**Comment by root-S7** [comment]
Did you install the shader paakage？

**Comment by Proaman7603** [comment]
Yeah pensa motion blur but i disabled it  and  again it is crashing and im getting resource pack reload failed in optifabric pls fix  it 🥺🥺

**Comment by Dcksp2468** [comment]
@Proaman7603 i got the same issue when using optifine (Poco M4 pro with mali G57, HelioG96, and 6 GB+)

**Comment by Proaman7603** [comment]
> @Proaman7603 i got the same issue when using optifine (Poco M4 pro with mali G57, HelioG96, and 6 GB+) , it crashes when using a Holy renderer instead of virGL. Maybe u can use virGL renderer instead

My phone doesn't support virgl and zink 😭😭😭
I think one of my mods is conflicting with each other or something like that because when I was using only optifabric and optifine, it was working fine

**Comment by Dcksp2468** [comment]
@Proaman7603 Just look up ur phone spec, looks like ur using PowerVR GE8320, am i correct? If so, no wonder, because some says on the internet that PowerVR devices have very poor support for rendering some games. Like on bedrock edition, u can't use Deferred PBR shader, which in simplified for me is a pipeline rendering shader that "closely" Resembles to Ray tracing. Maybe that also affects ur gameplay on Mc java. If u maybe want to get better gaming experience, maybe u should get a better phone with snapdragon, because those are the "gaming" chipset for phone, but its very pricey, so if u don't want to buy a new one, its ok, its not ur fault. Feel sorry for u bud
